import { defineConfig } from 'oxlint'

export default defineConfig({
	categories: {
		correctness: 'error',
		suspicious: 'error',
		perf: 'error',
	},
	plugins: ['typescript', 'vitest', 'unicorn', 'import', 'node', 'promise'],
	jsPlugins: [
		{ name: 'anti-slop', specifier: './tools/oxlint/anti-slop/index.ts' },
		{ name: 'anti-slop-effect', specifier: './tools/oxlint/anti-slop/effect/index.ts' },
	],
	rules: {
		'complexity': ['error', 8],
		'eqeqeq': 'error',
		'max-depth': ['error', 3],
		'max-lines-per-function': ['error', 120],
		'max-params': ['error', 4],
		'oxc/no-accumulating-spread': 'error',
		'anti-slop/no-array-filter-map': 'error',
		'anti-slop/no-reduce-accumulator-copy': 'error',
		'anti-slop/no-chained-type-assertions': 'error',
		'anti-slop/no-conditional-empty-object-spread': 'error',
		'anti-slop/no-known-value-widening': 'error',
		'anti-slop/no-module-mocking': 'error',
		'anti-slop/no-object-parameters': 'error',
		'anti-slop/no-reflect-apply': 'error',
		'anti-slop/no-reflect-get': 'error',
		'anti-slop/no-runtime-typeof': 'error',
		'anti-slop/no-shape-in-symbol-names': 'error',
		'anti-slop/no-unknown-parameters': 'error',
		'anti-slop/no-unknown-returns': 'error',
		'anti-slop/no-unknown-type-aliases': 'error',
		'anti-slop/no-unsafe-dictionary-type': 'error',
		'anti-slop/no-widen-then-assert': 'error',
		'anti-slop/require-readable-spacing': 'error',
		'anti-slop/require-safety-comment-for-type-assertion': 'error',
		'anti-slop-effect/no-manual-effect-error-tag': 'error',
		'anti-slop-effect/no-manual-tag-comparison': 'error',
		'anti-slop-effect/no-manual-tagged-construction': 'error',
		'anti-slop-effect/no-service-constructor-imports': 'error',
		'anti-slop-effect/prefer-effect-match': 'error',
		'no-console': 'error',
		'no-else-return': 'error',
		'no-new': 'off',
		'no-underscore-dangle': ['error', { allow: ['_tag'] }],
		'no-unused-vars': 'error',
		'import/no-cycle': 'error',
		'import/no-default-export': 'error',
		'import/no-self-import': 'error',
		'node/no-process-env': 'error',
		'typescript/explicit-function-return-type': 'error',
		'typescript/explicit-module-boundary-types': 'error',
		'typescript/no-explicit-any': 'error',
		'typescript/no-floating-promises': 'error',
		'typescript/no-import-type-side-effects': 'error',
		'typescript/no-misused-promises': 'error',
		'typescript/no-non-null-assertion': 'error',
		'typescript/no-unnecessary-type-assertion': 'error',
		'typescript/no-unsafe-argument': 'error',
		'typescript/no-unsafe-assignment': 'error',
		'typescript/no-unsafe-call': 'error',
		'typescript/no-unsafe-member-access': 'error',
		'typescript/no-unsafe-return': 'error',
		'typescript/only-throw-error': 'error',
		'typescript/prefer-nullish-coalescing': 'error',
		'typescript/restrict-plus-operands': 'error',
		'typescript/strict-boolean-expressions': 'error',
		'typescript/switch-exhaustiveness-check': 'error',
		'typescript/use-unknown-in-catch-callback-variable': 'error',
		'unicorn/filename-case': ['error', { case: 'kebabCase' }],
		'unicorn/prefer-node-protocol': 'error',
		'vitest/expect-expect': [
			'error',
			{ assertFunctionNames: ['expect', 'expect*', 'assert', 'assert*'] },
		],
		'vitest/no-standalone-expect': 'off',
	},
	overrides: [
		{
			files: ['oxlint.config.ts', 'vitest.config.ts', 'src/main.ts'],
			rules: {
				'import/no-default-export': 'off',
			},
		},
		{
			files: ['src/lanes-forest-plugin.ts'],
			rules: {
				'anti-slop/no-unknown-parameters': 'off',
				'anti-slop/no-unknown-returns': 'off',
				'typescript/no-unsafe-assignment': 'off',
				'typescript/no-unsafe-type-assertion': 'off',
			},
		},
		{
			files: ['src/lanes-apply-card-drop.ts', 'src/lanes-create-column-note.ts'],
			rules: {
				'typescript/no-unsafe-argument': 'off',
				'typescript/no-unsafe-member-access': 'off',
				'typescript/no-unsafe-type-assertion': 'off',
			},
		},
		{
			files: ['esbuild.config.mjs', 'version-bump.mjs'],
			rules: {
				'no-console': 'off',
				'node/no-process-env': 'off',
				'typescript/no-unsafe-assignment': 'off',
				'typescript/no-unsafe-member-access': 'off',
			},
		},
		{
			files: ['**/*.test.ts'],
			rules: {
				'complexity': 'off',
				'max-lines-per-function': 'off',
				'typescript/explicit-function-return-type': 'off',
				'typescript/explicit-module-boundary-types': 'off',
			},
		},
	],
	ignorePatterns: [
		'**/node_modules/**',
		'**/dist/**',
		'**/coverage/**',
		'main.js',
		'.agent/**',
		'.agents/**',
		'.claude/**',
		'.codex/**',
		'.continue/**',
		'.cursor/**',
		'.gemini/**',
		'.opencode/**',
		'.pi/**',
		'.roo/**',
		'.windsurf/**',
		'tools/oxlint/anti-slop/**',
		'**/*.d.ts',
	],
	options: {
		typeAware: true,
		maxWarnings: 0,
	},
})
